# pnpmワークスペース設定
# フロントエンド（Svelte）プロジェクトをワークスペースのルートとして管理

packages:
  # ルートディレクトリ（フロントエンド）
  - "."
  
  # 将来的に追加パッケージがある場合のための設定
  # - "packages/*"
  # - "apps/*"

minimumReleaseAge: 2880
# Tauriバックエンド（src-tauri）はRustプロジェクトなので
# pnpmワークスペースには含めない