# pnpmワークスペース設定
# デスクトップアプリケーション（Svelte + Tauri）をpackages/desktop配下で管理

packages:
  # デスクトップアプリケーション
  - "packages/desktop"
  
  # 将来的に追加パッケージがある場合のための設定
  - "packages/*"

minimumReleaseAge: 2880
# Tauriバックエンド（src-tauri）はRustプロジェクトなので
# pnpmワークスペースには含めない